export enum BadgeType {
  Local_Kolektivo_Multi_Sig_Member = 0,
  Reserve_Arbitrageur = 2,
  Treasury_Arbitrageur = 3,
  Topology_Data_Delegate = 4,
  Ecology_Data_Delegate = 5,
  Treasury_Delegate = 6,
  Reserve_Monetary_Delegate = 7,
  Kolektivo_Network_Multi_Sig_Member = 8,
  MONETARY_CONTROLLER = 1,
  MONETARY_DELEGATE = 100,
  VETO_DELEGATE = 101,
  TOPOLOGY_DELEGATE = 102,
  ECOLOGY_DELEGATE = 103,
  ECOLOGY_DELEGATE_MANAGER = 104,
  MONETARY_DELEGATE_MANAGER = 105,
  TOPOLOGY_DELEGATE_MANAGER = 106,
  VETO_DELEGATE_MANAGER = 107,
  ECOLOGY_DELEGATE_PROPOSER = 108,
}
