export enum BadgeType {
  MONETARY_CONTROLLER = 1,
  RESERVE_DELEGATE = 2,
  RESERVE_VETO_DELEGATE = 3,
  TOPOLOGY_DELEGATE = 4,
  ECOLOGY_DELEGATE = 5,
  ECOLOGY_DELEGATE_PROPOSER = 6,
  RESERVE_ARBITRAGEUR = 7,
  LOCAL_MULTI_SIG_MEMBER = 8,
  TREASURY_DELEGATE = 101,
  TREASURY_VETO_DELEGATE = 102,
  TREASURY_ARBITRAGEUR = 103,
  KOLEKTIVO_MULTI_SIG_MEMBER = 104,
}
