export enum BadgeType {
  MONETARY_CONTROLLER = 1,
  MONETARY_DELEGATE = 100,
  VETO_DELEGATE = 101,
  TOPOLOGY_DELEGATE = 102,
  ECOLOGY_DELEGATE = 103,
  ECOLOGY_DELEGATE_MANAGER = 104,
  MONETARY_DELEGATE_MANAGER = 105,
  TOPOLOGY_DELEGATE_MANAGER = 106,
  VETO_DELEGATE_MANAGER = 107,
  ECOLOGY_DELEGATE_PROPOSER = 108,
}
