name: Trigger scheduled tasks on a CRON Schedule
on:
  schedule:
    # Runs every 5 minutes (see https://crontab.guru)
    - cron: '*/5 * * * *'
jobs:
  build:
    name: Trigger Chart Data Refresh
    runs-on: ubuntu-latest
    steps:
      - name: node script
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: node ./scripts/update-chart-data.mjs
