name: Trigger scheduled tasks on a CRON Schedule
on:
  push:
    branches:
      - main
      - staging
      - development
  schedule:
    # Runs every 5 minutes (see https://crontab.guru)
    - cron: '* * * * *'
jobs:
  build:
    name: Trigger Chart Data Refresh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: node ./scripts/update-chart-data.mjs
